security:
    encoders:
        App\Entity\User: bcrypt

    providers:
        our_users:
            entity: { class: App\Entity\User, property: username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
#            pattern: ^/
#            form_login:
#                login_path: login
#                check_path: login_check
#                always_use_default_target_path:  true
#                default_target_path:  /
            logout:
                path: /logout


    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
