language: php

php: 
  - 7.2.1

git:
  depth: 1

services:
  - mysql

before_install:
  - composer self-update
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
  - composer install
  - cp .env .env.dist
  - bin/console doctrine:database:create --env=test
  - bin/console doctrine:schema:create --env=test
  - bin/console doctrine:fixtures:load -n --env=test

script:
  - bin/phpunit

notifications:
  email: julienbutty@gmail.com






